export const FONT_OPTIONS = [
  {
    key: 'default',
    value: '',
    text: 'Default',
    style: { fontFamily: 'inherit' },
  },
  // Modern Sans-Serif Fonts
  {
    key: 'inter',
    value: 'font-inter',
    text: 'Inter',
    style: { fontFamily: 'Inter, sans-serif' },
  },
  {
    key: 'metropolis',
    value: 'font-metropolis',
    text: 'Metropolis',
    style: { fontFamily: 'Metropolis, sans-serif' },
  },
  {
    key: 'poppins',
    value: 'font-poppins',
    text: 'Poppins',
    style: { fontFamily: 'Poppins, sans-serif' },
  },
  {
    key: 'roboto',
    value: 'font-roboto',
    text: 'Roboto',
    style: { fontFamily: 'Roboto, sans-serif' },
  },
  {
    key: 'lato',
    value: 'font-lato',
    text: 'Lato',
    style: { fontFamily: 'Lato, sans-serif' },
  },
  // System Fonts
  {
    key: 'arial',
    value: 'font-arial',
    text: 'Arial',
    style: { fontFamily: 'Arial, sans-serif' },
  },
  {
    key: 'helvetica',
    value: 'font-helvetica',
    text: 'Helvetica',
    style: { fontFamily: 'Helvetica, sans-serif' },
  },
  // Elegant Serif Fonts
  {
    key: 'playfair',
    value: 'font-playfair',
    text: 'Playfair Display',
    style: { fontFamily: 'Playfair Display, serif' },
  },
  {
    key: 'merriweather',
    value: 'font-merriweather',
    text: 'Merriweather',
    style: { fontFamily: 'Merriweather, serif' },
  },
  {
    key: 'crimsontext',
    value: 'font-crimsontext',
    text: 'Crimson Text',
    style: { fontFamily: 'Crimson Text, serif' },
  },
  // Classic Fonts
  {
    key: 'georgia',
    value: 'font-georgia',
    text: 'Georgia',
    style: { fontFamily: 'Georgia, serif' },
  },
  {
    key: 'times',
    value: 'font-times',
    text: 'Times New Roman',
    style: { fontFamily: 'Times New Roman, serif' },
  },
  // Expressive/Playful Fonts
  {
    key: 'rubikspraypaint',
    value: 'font-rubikspraypaint',
    text: 'Rubik Spray Paint',
    style: { fontFamily: 'Rubik Spray Paint, cursive' },
  },
  // Business/Professional Fonts
  {
    key: 'dmseriftext',
    value: 'font-dmseriftext',
    text: 'DM Serif Text',
    style: { fontFamily: 'DM Serif Text, serif' },
  },
  {
    key: 'sansation',
    value: 'font-sansation',
    text: 'Sansation',
    style: { fontFamily: 'Sansation, sans-serif' },
  },
  {
    key: 'notoserif',
    value: 'font-notoserif',
    text: 'Noto Serif',
    style: { fontFamily: 'Noto Serif, serif' },
  },
  {
    key: 'opensans',
    value: 'font-opensans',
    text: 'Open Sans',
    style: { fontFamily: 'Open Sans, sans-serif' },
  },
  {
    key: 'montserrat',
    value: 'font-montserrat',
    text: 'Montserrat',
    style: { fontFamily: 'Montserrat, sans-serif' },
  },
  {
    key: 'nunito',
    value: 'font-nunito',
    text: 'Nunito',
    style: { fontFamily: 'Nunito, sans-serif' },
  },
  {
    key: 'nunitosans',
    value: 'font-nunitosans',
    text: 'Nunito Sans',
    style: { fontFamily: 'Nunito Sans, sans-serif' },
  },
  {
    key: 'lora',
    value: 'font-lora',
    text: 'Lora',
    style: { fontFamily: 'Lora, serif' },
  },
  {
    key: 'raleway',
    value: 'font-raleway',
    text: 'Raleway',
    style: { fontFamily: 'Raleway, sans-serif' },
  },
  {
    key: 'pacifico',
    value: 'font-pacifico',
    text: 'Pacifico',
    style: { fontFamily: 'Pacifico, cursive' },
  },
  {
    key: 'bebasneue',
    value: 'font-bebasneue',
    text: 'Bebas Neue',
    style: { fontFamily: 'Bebas Neue, sans-serif' },
  },
  {
    key: 'oswald',
    value: 'font-oswald',
    text: 'Oswald',
    style: { fontFamily: 'Oswald, sans-serif' },
  },
  {
    key: 'dancingscript',
    value: 'font-dancingscript',
    text: 'Dancing Script',
    style: { fontFamily: 'Dancing Script, cursive' },
  },
  {
    key: 'satisfy',
    value: 'font-satisfy',
    text: 'Satisfy',
    style: { fontFamily: 'Satisfy, cursive' },
  },
  {
    key: 'handlee',
    value: 'font-handlee',
    text: 'Handlee',
    style: { fontFamily: 'Handlee, cursive' },
  },
  {
    key: 'indieflower',
    value: 'font-indieflower',
    text: 'Indie Flower',
    style: { fontFamily: 'Indie Flower, cursive' },
  },
  // Calm/Peaceful Fonts
  {
    key: 'sourceserifpro',
    value: 'font-sourceserifpro',
    text: 'Source Serif Pro',
    style: { fontFamily: 'Source Serif Pro, serif' },
  },
  {
    key: 'librebaskerville',
    value: 'font-librebaskerville',
    text: 'Libre Baskerville',
    style: { fontFamily: 'Libre Baskerville, serif' },
  },
  {
    key: 'cormorantgaramond',
    value: 'font-cormorantgaramond',
    text: 'Cormorant Garamond',
    style: { fontFamily: 'Cormorant Garamond, serif' },
  },
  {
    key: 'ebgaramond',
    value: 'font-ebgaramond',
    text: 'EB Garamond',
    style: { fontFamily: 'EB Garamond, serif' },
  },
  {
    key: 'spectral',
    value: 'font-spectral',
    text: 'Spectral',
    style: { fontFamily: 'Spectral, serif' },
  },
  {
    key: 'alegreya',
    value: 'font-alegreya',
    text: 'Alegreya',
    style: { fontFamily: 'Alegreya, serif' },
  },
  // Professional Business Fonts
  {
    key: 'worksans',
    value: 'font-worksans',
    text: 'Work Sans',
    style: { fontFamily: 'Work Sans, sans-serif' },
  },
  {
    key: 'ibmplexsans',
    value: 'font-ibmplexsans',
    text: 'IBM Plex Sans',
    style: { fontFamily: 'IBM Plex Sans, sans-serif' },
  },
  {
    key: 'firasans',
    value: 'font-firasans',
    text: 'Fira Sans',
    style: { fontFamily: 'Fira Sans, sans-serif' },
  },
  {
    key: 'ptsans',
    value: 'font-ptsans',
    text: 'PT Sans',
    style: { fontFamily: 'PT Sans, sans-serif' },
  },
  {
    key: 'sourcesanspro',
    value: 'font-sourcesanspro',
    text: 'Source Sans Pro',
    style: { fontFamily: 'Source Sans Pro, sans-serif' },
  },
];

// List of all font style properties for easy management
export const FONT_STYLE_PROPS = [
  'style-font-inter',
  'style-font-metropolis',
  'style-font-poppins',
  'style-font-roboto',
  'style-font-lato',
  'style-font-arial',
  'style-font-helvetica',
  'style-font-playfair',
  'style-font-merriweather',
  'style-font-crimsontext',
  'style-font-georgia',
  'style-font-times',
  'style-font-rubikspraypaint',
  'style-font-dmseriftext',
  'style-font-sansation',
  'style-font-notoserif',
  'style-font-opensans',
  'style-font-montserrat',
  'style-font-nunito',
  'style-font-nunitosans',
  'style-font-lora',
  'style-font-raleway',
  'style-font-pacifico',
  'style-font-bebasneue',
  'style-font-oswald',
  'style-font-dancingscript',
  'style-font-satisfy',
  'style-font-handlee',
  'style-font-indieflower',
  'style-font-sourceserifpro',
  'style-font-librebaskerville',
  'style-font-cormorantgaramond',
  'style-font-ebgaramond',
  'style-font-spectral',
  'style-font-alegreya',
  'style-font-worksans',
  'style-font-ibmplexsans',
  'style-font-firasans',
  'style-font-ptsans',
  'style-font-sourcesanspro',
];
