const addons = [
  '@eeacms/volto-accordion-block',
  '@kitconcept/volto-banner-block',
  '@kitconcept/volto-button-block',
  '@kitconcept/volto-carousel-block',
  '@kitconcept/volto-heading-block',
  '@kitconcept/volto-highlight-block',
  '@kitconcept/volto-introduction-block',
  '@kitconcept/volto-logos-block',
  '@kitconcept/volto-separator-block',
  '@kitconcept/volto-slider-block',
  // '@eeacms/volto-tabs-block',
  '@eeacms/volto-group-block',
  '@eeacms/volto-columns-block',
  '@eeacms/volto-block-divider',
  '@eeacms/volto-statistic-block',
  '@eeacms/volto-pdf-block',
  '@eeacms/volto-slate-footnote',
  '@eeacms/volto-block-toc',
  '@eeacms/volto-metadata-block',
  '@eeacms/volto-quote-block',
  '@eeacms/volto-tags-block',
  '@plone-collective/volto-footer',
  'lunasites-advanced-styling',
  'volto-lunasites',
  'luna-super-listing',
  'luna-super-hero',
  'luna-super-tabs',
];

module.exports = {
  addons,
};
